Models/Product.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Onlinestore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.Carts = new HashSet<Cart>();
            this.Orders = new HashSet<Order>();
        }
    
        public int product_id { get; set; }
        public string product_name { get; set; }
        public decimal product_price { get; set; }
        public int category_id { get; set; }
        public string productimg { get; set; }
        public Nullable<int> quantity { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cart> Carts { get; set; }
        public virtual Category Category { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order> Orders { get; set; }
    }
}

Controllers/CartsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Onlinestore.Models;

namespace Onlinestore.Controllers
{
    public class CartsController : Controller
    {
        private OnlinestoreEntities db = new OnlinestoreEntities();

        // GET: MyCart


        public ActionResult CartView()

        {
            List<Cart> cart = Session["Cart"] as List<Cart>;
            if (cart == null)

            {

                cart = new List<Cart>();

                Session["Cart"] = cart;

            }

            return View(cart);

        }

        public ActionResult PaidView()

        {

            return View();

        }
        // GET: Products/AddToCart

        [HttpPost]

        public ActionResult AddToCart(int id, decimal price, int quantity = 1)

        {

            List<Cart> cart = Session["Cart"] as List<Cart> ?? new List<Cart>();

            Cart existingItem = cart.FirstOrDefault(item => item.cart_id == id);

            if (existingItem != null)

            {

                existingItem.quantity += quantity;

            }

            else

            {

                cart.Add(new Cart { cart_id = id, price = Convert.ToInt32(price), quantity = quantity });

            }

            Session["Cart"] = cart;

            return RedirectToAction("CartView");

        }

        public ActionResult RemoveFromCart(int id)

        {

            List<Cart> cart = Session["Cart"] as List<Cart>;

            if (cart != null)

            {

                cart.RemoveAll(item => item.cart_id == id);

                Session["Cart"] = cart;

            }

            return RedirectToAction("CartView");

        }

        public int GetCurrentUserId()

        {
            return 1;

        }

        public ActionResult Checkout()

        {

            // Retrieve cart items from session

            List<Cart> cartItems = Session["Cart"] as List<Cart>;

            if (cartItems == null || cartItems.Count == 0)

            {

                // Redirect to an empty cart page or display a message

                return RedirectToAction("EmptyCart");

            }

            // Calculate total amount

            int price = (int)cartItems.Sum(item => (item.price * item.quantity));

            // Create a new order

            var buy = new Order

            {

                order_id = GetCurrentUserId(), // Replace with actual logic to get the current user ID

                total_price = price,

                order_date = DateTime.Now,

                // Set the initial order status

            };

            // Save the order to the database
            db.Orders.Add(buy);

            db.SaveChanges();

            // Optionally, you can clear the cart session after creating the order

            Session["Cart"] = null;

            // Redirect to the order confirmation page with the order ID

            return RedirectToAction("PaidView", new { orderId = buy.order_id });

        }
        public ActionResult Paid()
        {
            return View();
        }

    }

}

Controllers/ProductsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Onlinestore.Models;

namespace Onlinestore.Controllers
{
    public class ProductsController : Controller
    {
        private OnlinestoreEntities db = new OnlinestoreEntities();

        // GET: Products
        public ActionResult Index()
        {
            var products = db.Products.Include(p => p.Category);
            return View(products.ToList());
        }

        // GET: Products/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Product product = db.Products.Find(id);
            if (product == null)
            {
                return HttpNotFound();
            }
            return View(product);
        }
        public ActionResult ProductView()
        {
            var products = db.Products.Include(p => p.Category);
            return View(products);

        }
        // GET: Products/Create
        public ActionResult Create()
        {
            ViewBag.category_id = new SelectList(db.Categories, "category_id", "name");
            return View();
        }

        // POST: Products/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "product_id,product_name,product_price,category_id,productimg")] Product product)
        {
            if (ModelState.IsValid)
            {
                db.Products.Add(product);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.category_id = new SelectList(db.Categories, "category_id", "name", product.category_id);
            return View(product);
        }

        // GET: Products/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Product product = db.Products.Find(id);
            if (product == null)
            {
                return HttpNotFound();
            }
            ViewBag.category_id = new SelectList(db.Categories, "category_id", "name", product.category_id);
            return View(product);
        }

        // POST: Products/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "product_id,product_name,product_price,category_id,productimg")] Product product)
        {
            if (ModelState.IsValid)
            {
                db.Entry(product).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.category_id = new SelectList(db.Categories, "category_id", "name", product.category_id);
            return View(product);
        }

        // GET: Products/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Product product = db.Products.Find(id);
            if (product == null)
            {
                return HttpNotFound();
            }
            return View(product);
        }

        // POST: Products/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Product product = db.Products.Find(id);
            db.Products.Remove(product);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Views/Products/Create.cshtml
@model Onlinestore.Models.Product

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h2>Create</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Product</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })


        <div class="form-group">
            @Html.LabelFor(model => model.product_name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.product_name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.product_name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.product_price, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.product_price, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.product_price, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.category_id, "category_id", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("category_id", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.category_id, "", new { @class = "text-danger" })
            </div>
        </div>
        <br />
        <div class="form-group">
            @Html.LabelFor(model => model.productimg, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.productimg, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.productimg, "", new { @class = "text-danger" })
            </div>
        </div>
        <br />
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Views/Products/Delete.cshtml
@model Onlinestore.Models.Product

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Product</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.product_name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.product_name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.product_price)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.product_price)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Category.name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Category.name)
        </dd>

    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-danger" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Views/Products/Details.cshtml
@model Onlinestore.Models.Product

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Product</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.product_name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.product_name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.product_price)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.product_price)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Category.name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Category.name)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.product_id }, new { @class = "btn btn-primary" }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Views/Products/Edit.cshtml
@model Onlinestore.Models.Product

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Product</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.product_id)

        <div class="form-group">
            @Html.LabelFor(model => model.product_name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.product_name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.product_name, "", new { @class = "text-danger" })
            </div>
        </div>
        <br />
        <div class="form-group">
            @Html.LabelFor(model => model.product_price, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.product_price, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.product_price, "", new { @class = "text-danger" })
            </div>
        </div>
        <br />

        <div class="form-group">
            @Html.LabelFor(model => model.category_id, "category_id", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("category_id", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.category_id, "", new { @class = "text-danger" })
            </div>
        </div>
        <br />
        <div class="form-group">
            @Html.LabelFor(model => model.productimg, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.productimg, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.productimg, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Views/Products/Index.cshtml
@model IEnumerable<Onlinestore.Models.Product>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create", new { area = "" }, new { @class = "btn btn-success" })
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.product_name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.product_price)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Category.name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.productimg)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.product_name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.product_price)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Category.name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.productimg)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.product_id }, new { @class = "btn btn-primary" })
                @Html.ActionLink("Details", "Details", new { id = item.product_id }, new { @class = "btn btn-success" })
                @Html.ActionLink("Delete", "Delete", new { id = item.product_id }, new { @class = "btn btn-danger" })
            </td>
        </tr>
    }

</table>

Views/Products/ProductView.cshtml
@model IEnumerable<Onlinestore.Models.Product>

@{
    ViewBag.Title = "ProductView";
    Layout = "~/Views/Shared/_CustomerLayout.cshtml";
}

<h2>ProductView</h2>


<style>
    .menu-item-image {
        width: 270px;
        height: 230px;
    }
</style>


<!-- plants -->
<div class="container" id="plant-cards">
    <h1 class="text-center">Our Collection</h1>
    <h2 class="text-center">Shop out the best Collection!</h2>
    <div class="row" style="margin-top: 30px;">
        <!-- shop items -->
        @foreach (var item in Model)
        {
            string MenuUrl = "https://localhost:44338/Content/images/" + @item.productimg;
            <div class="col-md-3 py-3 py-md-0">
                @using (Html.BeginForm("AddToCart", "Carts", new { id = item.product_id, price = item.product_price }, FormMethod.Post))
                {
                    <div class="menu">

                        <img class="menu-item-image" src="@MenuUrl" alt="@item.productimg">
                        <h2 class="menu-item-category">@item.product_name</h2>
                        <h4 class="menu-item-price">Rs.@item.product_price</h4>
                    </div>
                    <div>
                        <h2 class="shop-item-price"> <span><input type="submit" value="Add To Cart" class="btn btn-primary" /></span></h2>
                    </div>
                }
            </div>
        }
    </div>
</div>